### ISSUE TITLE
karma-electron crashes when using electron version 1.4.3

### ISSUE THREAD

**Issue by etiennejcharles** [twolfson/karma-electron#16] opened 2016-10-06 18:06 UTC
When using electron version 1.4.3 this is the error I get.

![image](https://cloud.githubusercontent.com/assets/2872476/19164391/c66c917c-8bcd-11e6-9b10-0873a6abb3d8.png)

I reverted to version 1.4.2

And my tests now again pass. 

![image](https://cloud.githubusercontent.com/assets/2872476/19164418/e13a901c-8bcd-11e6-8c2b-a0bc85db3e9d.png)

Do you get the same error?

**Comment by twolfson** [comment] 2016-10-06 23:58
I'm seeing failures in 1.4.3 as well yet 1.4.2 is passing. I don't see any relevant issues since 1.4.3's release. I've done a little bit of debugging and it looks like something in Karma's setup as loading http://google.com/ works fine.

**Comment by twolfson** [comment] 2016-10-07 00:06
I moved to launching Karma in its continuous mode and launching `electron` directly. This is the error we are getting:

``` js
$ ./node_modules/.bin/electron lib/electron-launcher.js --url http://localhost:9876/
/home/todd/github/karma-electron/lib/electron-launcher.js:4
  throw err;
  ^

TypeError: Cannot set property 'openerId' of undefined
    at mergeBrowserWindowOptions (/home/todd/github/karma-electron/node_modules/electron/dist/resources/electron.asar/browser/guest-window-manager.js:44:35)
    at EventEmitter.<anonymous> (/home/todd/github/karma-electron/node_modules/electron/dist/resources/electron.asar/browser/guest-window-manager.js:144:13)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/home/todd/github/karma-electron/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by twolfson** [comment] 2016-10-07 00:08
I'm going to try setting up a minimal gist to reproduce the error and opening an issue on `electron`.

**Comment by twolfson** [comment] 2016-10-07 00:23
Alright, the issue has been reported in https://github.com/electron/electron/issues/7519. For now, I suggest sticking to Electron@1.4.2

**Comment by yaooluu** [comment] 2016-10-07 19:50
@etiennejcharles I'm having the exact same issue. Thanks for reporting it and the downgrade suggestion.

@twolfson Thanks for the detailed trace of this issue! I've learned from it. :)

**Comment by twolfson** [comment] 2016-10-24 06:05
Electron@1.4.4 has been released and it looks like the issue has been resolved. Closing this issue

**Closed as completed by twolfson** 2016-10-24 06:05 UTC
Labels: bug, blocked
