### ISSUE TITLE
Uncaught TypeError: Function.prototype.toString is not generic

### ISSUE THREAD

**Issue by GProst** [twolfson/karma-electron#20] opened 2017-03-09 11:28 UTC
Full stacktrace:
```
Uncaught TypeError: Function.prototype.toString is not generic
at http://localhost:9876/context.js:23
```

In context.js file I `console.info()` that function name and it shows `electron`'s internal `remoteMemberFunction` function.

In my app I use `electron`'s `remote.require('moduleName')` several times. I think it may be important cause `remoteMemberFunction` is defined in `electron`'s` renderer/api/remote.js` file.

I start karma via `karma start`. After replacing `
      return obj.toString().replace(/\{[\s\S]*\}/, '{ ... }')` line in content.js with `return;` karma seems to work fine (this is my temporal decision of solving problem).

Here is my karma.conf:

```
module.exports = function(config) {
  config.set({
    basePath: './',
    frameworks: ['jasmine'],

    files: [
      'app/app.js', // this is a webpack app bundle with angular.js
      'node_modules/angular-mocks/angular-mocks.js',
      'src/**/*.html',
      'src/**/*spec.js'
    ],
    
    client: {
      useIframe: false
    },

    exclude: [
      'src/node_modules/**/*spec.js',
      'src/node_modules/**/*.html''
    ],

    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'app/app.js': ['electron']
    },
    
    ngHtml2JsPreprocessor: {
      stripPrefix: 'src/',
      moduleName: 'appTemplates'
    },

    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    singleRun: false,
    concurrency: Infinity,

    browsers: ['Electron'],
    
    plugins: [
      'karma-electron',
      'karma-jasmine',
      'karma-ng-html2js-preprocessor'
    ]
  });
};
```

Thank you in advance!

**Comment by GProst** [comment] 2017-03-09 11:36
Packages versions:
electron: 1.6.2
karma: 1.5.0
karma-electron: 5.1.1
karma-jasmine: 1.1.0
karma-ng-html2js-preprocessor: 1.0.0
angular: 1.6.2
angular-mocks: 1.6.2

**Comment by twolfson** [comment] 2017-03-09 21:18
Thanks for the detailed bug report. I'm not sure what would cause this so we'll definitely need to triage. I'll perform a triage by the end of the weekend

**Comment by twolfson** [comment] 2017-03-10 05:17
We have successfully reproduced the error. We were able to reproduce with something as simple as:

```js
var electron = require('electron');
console.log(electron);
```

My hunch is this is an issue in Karma's serializer due to Electron using some native modules but I'll keep on digging

**Comment by twolfson** [comment] 2017-03-10 06:17
Okay, we've traced down the source of this issue. `electron` is using a `Proxy` constructor for its remote functions:

https://github.com/electron/electron/blob/v1.6.3/lib/renderer/api/remote.js#L170-L190

Proxies cannot be serialized without causing a `TypeError`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString

```js
new Proxy(function x () {}, {}).toString()
// VM594:1 Uncaught TypeError: Function.prototype.toString is not generic
//    at Proxy.toString (<anonymous>)
//    at <anonymous>:1:33
```

Unfortunately, proxies can't be detected either (due to them being proxies -- intentionally transparent). However, we can detect them having serialization issues and provide a fallback.

```js
case 'function':
  try {
    return obj.toString().replace(/\{[\s\S]*\}/, '{ ... }')
  } catch (err) {
    if (err instanceof TypeError) {
      return 'Proxy(function ' + (obj.name || '') + '(...) { ... })';
    } else {
      throw err;
    }
  }
```

which yields:

```
Object{clipboard: Object{availableFormats: Proxy(function remoteMemberFunction(...) { ... }), has: Proxy(function remoteMemberFunction(...) { ... }), 
```

Our plan of action is 2 part:

- Add a `try/catch` to Karma so it falls back when encountering proxies
- Add `toString` logic to Electron's `Proxy` wrapper

```
new Proxy(function x () {}, {get: function () { return function () { return x.toString() }; }}).toString()
// "function x() {}"
```

**Comment by twolfson** [comment] 2017-03-10 06:19
As a workaround for you, you should be able to use a fork of Karma with the patched serializer (which it seems you're already doing). This can be formalized by a `git+ssh` URL but whatever works for you :+1: 

https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by twolfson** [comment] 2017-03-10 06:39
Okay, 1 PR down -- Karma https://github.com/karma-runner/karma/issues/2595. 1 PR to go

**Comment by twolfson** [comment] 2017-03-10 07:38
Finally got the repo locally bootstrapped. Took a lot longer than I expected because I missed the quick bootstrap notes again:

https://github.com/electron/electron/blob/v1.6.3/docs/development/build-system-overview.md#minimal-bootstrapping

**Comment by twolfson** [comment] 2017-03-10 08:10
Alright, second PR is open: https://github.com/electron/electron/pull/8890

Since this issue is not specific to our repo at all, we are going to close it. Thanks for the bug report and finding that edge case =)

**Closed as completed by twolfson** 2017-03-10 08:10 UTC
Labels: bug, help wanted

**Comment by GProst** [comment] 2017-03-10 08:42
Great! Thanks for being quick to react, I will look forward for your PR's to be merged and released.
