### ISSUE TITLE
Cannot find module 'path'

### ISSUE THREAD

**Issue by j-a-m-l** [twolfson/karma-electron#27] opened 2017-11-06 17:24 UTC
I'm trying to add some tests for [ARK desktop wallet](https://github.com/ArkEcosystem/ark-desktop). In this project, the Angular.js app is requiring Node.js modules (on [package.json](https://github.com/ArkEcosystem/ark-desktop/blob/master/client/package.json)), so using `karma-electron` is a way to loading those modules.

I've changed the `preprocessors` and `browsers` of the [Karma.js configuration](https://github.com/ArkEcosystem/ark-desktop/blob/master/test/karma.conf.js), but I'm having problems:

An error "Cannot find module 'path'" is triggered from `node_modules/mocha/mocha.js:1`. That files re-implements the `require` function at the beginning.

**Comment by twolfson** [comment] 2017-11-06 18:13
I can't seem to find the `karma-electron` integration on any branch. Can you link me to it?

**Comment by j-a-m-l** [comment] 2017-11-06 20:34
Sorry @twolfson , I didn't push any commit with my attempts.

But now, since you asked about it, I've pushed a branch to my forked repo with some temporal changes:
https://github.com/j-a-m-l/ark-desktop/tree/debug-karma-electron

**Comment by twolfson** [comment] 2017-11-06 20:37
The issue is you're missing the `useIframe: false`. We need this to properly use `require` across multiple levels of node modules. Closing issue eagerly

**Closed as completed by twolfson** 2017-11-06 20:37 UTC
Labels: question

**Comment by j-a-m-l** [comment] 2017-11-06 22:20
Thanks @twolfson.

That wasn't right, but now the errors is: "Cannot read 'concat' of undefined". Replacing
```js
module.paths = module.paths.concat(__require('module')._nodeModulePaths('{{!karmaBasePath}}'));
```
with
```js
module.paths = (module.paths || []).concat(__require('module')._nodeModulePaths('{{!karmaBasePath}}'));
```
would fix it.

But it would trigger other problem: "Maximum call stack size exceeded".

**Comment by twolfson** [comment] 2017-11-07 08:23
I looked into this a bit and that error is being caused by `angular-mocks.js` overwriting Node.js' definition of `module` which is leading to a sticky situation

After disabling `angular-mocks`, I'm seeing the "Maximum call stack size exceeded" between our `window.require` definition and Mocha's wrapper. I'm looking into why this doesn't happen in our other frameworks

**Comment by twolfson** [comment] 2017-11-07 08:26
Also, fwiw, I disabled `coverage` so the stack traces are more legible -- especially via the "Debug" window (requires disabling `--single-run` and opening via "Debug" button)

**Comment by twolfson** [comment] 2017-11-07 08:36
It looks like the issue is being caused by `4.0.0` version of mocha (released about 1 month ago) which overwrites the global `require`. Downgrading to `3.5.3` fixed the issue and moved to a new one for Angular in the repo's domain:

```
Electron 1.8.1 (Node 8.2.1) ERROR
  Uncaught TypeError: module is not a function
  at services/network.service.js:23
```

which corresponds to:

```js
describe('networkService', function () {
  beforeEach(module('arkclient.services'))
```

It looks like there's already a Mocha `require=` related issue so I'd suggest subscribing to that and using a downgraded version for now:

https://github.com/mochajs/mocha/issues/3091

**Comment by j-a-m-l** [comment] 2017-11-07 15:34
Thank you very much for all your help.
