### ISSUE TITLE
Specify Karma version compatibility

### ISSUE THREAD

**Issue by pirelenito** [twolfson/karma-electron#13] opened 2016-09-14 19:42 UTC
Hi there! Awesome project!

I am having issues making the launcher run and it looks like it is because my Karma version was older than the required one.

I looked into [this Karma PR](https://github.com/karma-runner/karma/pull/1984) and it seems that `karma-electron` requires Karma at least `1.1.0`, is that so?

If that is correct, should we add it as a `peerDependency`? I can prepare a PR.

**Comment by twolfson** [comment] 2016-09-14 20:01
We do require at least `karma@1.1.0`. I figured we wouldn't need to document/introduce that because people who are installing `karma-electron` will typically only be using this plugin which means their `karma` install would be fresh.

In addition to that, I would prefer to avoid `peerDependencies` as they typically cause more headaches than solve any:

https://github.com/npm/npm/issues/5080

How about we add something to the README as a compromise?

**Comment by pirelenito** [comment] 2016-09-14 20:36
On **npm 3** this shouldn't be a problem anymore, given it doesn't install `peerDependencies` automatically. Its purpose is simply to warn any consumer of the package that you need to install extra dependencies for it to work.

If you still are not comfortable in adding it as a `peerDependencies` I would do as you suggest and add a notice in the README.

Thanks again!

**Comment by pirelenito** [comment] 2016-09-14 20:36
Either way you decide to go, I can prepare a PR.

**Comment by twolfson** [comment] 2016-09-14 23:18
Ah, that's a good solution for `npm@3`. Unfortunately, a lot of users (myself included) are still using `npm@2` (my reason is this blocker issue hasn't bee resolved to my knowledge -- https://github.com/npm/npm/issues/10119)

I think the README is the best solution. We should probably also list the version of Electron we have tested against.

I will take care of the README update -- I'm typically picky about what's said/where so I don't want to waste any of your time with back and forth. I will take care of that by the end of the weekend.

For my own reference, how were you using `karma` before `karma-electron`? (e.g. using PhantomJS but with a bundler)

**Comment by pirelenito** [comment] 2016-09-15 08:25
Awesome, thanks!

I still use Karma with PhantomJS for my regular web projects. You can check how I set it up in [Sagui](https://github.com/saguijs/sagui) a tool to build frontend projects.

My use-case with your library is to test an actual Electron app.

Would you suggest using it for regular web applications as well? And why?

**Comment by twolfson** [comment] 2016-09-15 08:44
This has been patched and released in `4.1.1`

**Closed as completed by twolfson** 2016-09-15 08:44 UTC

**Comment by twolfson** [comment] 2016-09-15 08:50
Ah, alright. Thanks for the context =)

As a heads up, this is best suited for only testing the renderer portion of an `electron` app (i.e. testing menus should be done via Electron and Selenium)

I wouldn't suggest using this for regular web apps. It's typically best to have the testing environment be as close to production as possible. This means the ideal scenario is using an actual browser (e.g. Chrome, Firefox), although both `electron` and PhantomJS suffice.

One scenario where it would annoyingly fail would be accidentally relying on something Node.js based but something is different in the browser polyfill (e.g. `Buffer`). One scenario where it would be nice is visual regression testing directly in the test suite (maybe using it as a secondary plugin, instead of exclusively).
